# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - syn-search-app

on:
  push:
    branches:
      - web_app
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://synsearch.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_484ba624919f4110bd5e8b31f1bbe8c3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_043d14cb04794c8cb1b624cfc727ae96 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: synsearch.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_484ba624919f4110bd5e8b31f1bbe8c3 }}/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'syn-search-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1be134fe6ce444de91bc4c72ff84c587 }}
        images: 'synsearch.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_484ba624919f4110bd5e8b31f1bbe8c3 }}/webimage:${{ github.sha }}'